import {
  Flame, Activity, Lightbulb, Thermometer, BarChart2, ShieldAlert,
  Layers, Cpu, Database, Zap, Settings, Wrench, Monitor, Server,
  Cloud, Code, Package, GitBranch, TrendingUp, PieChart,
  Gauge, Target, Factory, Cog, Anchor, Building, Hammer,
  FlaskConical, Microscope, Radar, Boxes, CircuitBoard, HardHat,
  Truck, FolderOpen, Clipboard, BarChart,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const ICON_MAP: Record<string, LucideIcon> = {
  "flame": Flame,
  "activity": Activity,
  "lightbulb": Lightbulb,
  "thermometer": Thermometer,
  "bar-chart-2": BarChart2,
  "shield-alert": ShieldAlert,
  "layers": Layers,
  "cpu": Cpu,
  "database": Database,
  "zap": Zap,
  "settings": Settings,
  "wrench": Wrench,
  "monitor": Monitor,
  "server": Server,
  "cloud": Cloud,
  "code": Code,
  "package": Package,
  "git-branch": GitBranch,
  "trending-up": TrendingUp,
  "pie-chart": PieChart,
  "gauge": Gauge,
  "target": Target,
  "factory": Factory,
  "cog": Cog,
  "anchor": Anchor,
  "building": Building,
  "hammer": Hammer,
  "flask-conical": FlaskConical,
  "microscope": Microscope,
  "radar": Radar,
  "boxes": Boxes,
  "circuit-board": CircuitBoard,
  "hard-hat": HardHat,
  "truck": Truck,
  "folder-open": FolderOpen,
  "clipboard": Clipboard,
  "bar-chart": BarChart,
};

export const DEFAULT_ICONS = Object.keys(ICON_MAP);
